<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Room extends \Application\Entity\Room implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function getBuild()
    {
        $this->__load();
        return parent::getBuild();
    }

    public function getStudents()
    {
        $this->__load();
        return parent::getStudents();
    }

    public function getHealths()
    {
        $this->__load();
        return parent::getHealths();
    }

    public function getRepairs()
    {
        $this->__load();
        return parent::getRepairs();
    }

    public function getElectric_bills()
    {
        $this->__load();
        return parent::getElectric_bills();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function setBuild($build)
    {
        $this->__load();
        return parent::setBuild($build);
    }

    public function addStudent($student)
    {
        $this->__load();
        return parent::addStudent($student);
    }

    public function addHealth($health)
    {
        $this->__load();
        return parent::addHealth($health);
    }

    public function addRepair($repair)
    {
        $this->__load();
        return parent::addRepair($repair);
    }

    public function addElectric_bill($electric_bill)
    {
        $this->__load();
        return parent::addElectric_bill($electric_bill);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getCreate_at()
    {
        $this->__load();
        return parent::getCreate_at();
    }

    public function setCreate_at($create_at)
    {
        $this->__load();
        return parent::setCreate_at($create_at);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'name', 'id', 'create_at', 'build', 'students', 'healths', 'repairs', 'electric_bills');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}