<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Student extends \Application\Entity\Student implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getBed_num()
    {
        $this->__load();
        return parent::getBed_num();
    }

    public function getStudent_num()
    {
        $this->__load();
        return parent::getStudent_num();
    }

    public function getReal_name()
    {
        $this->__load();
        return parent::getReal_name();
    }

    public function getGender()
    {
        $this->__load();
        return parent::getGender();
    }

    public function getCollege()
    {
        $this->__load();
        return parent::getCollege();
    }

    public function getSpecialty()
    {
        $this->__load();
        return parent::getSpecialty();
    }

    public function getGrade()
    {
        $this->__load();
        return parent::getGrade();
    }

    public function getClass()
    {
        $this->__load();
        return parent::getClass();
    }

    public function getPhone()
    {
        $this->__load();
        return parent::getPhone();
    }

    public function getCheckin()
    {
        $this->__load();
        return parent::getCheckin();
    }

    public function getRoom()
    {
        $this->__load();
        return parent::getRoom();
    }

    public function getUser()
    {
        $this->__load();
        return parent::getUser();
    }

    public function setBed_num($bed_num)
    {
        $this->__load();
        return parent::setBed_num($bed_num);
    }

    public function setStudent_num($student_num)
    {
        $this->__load();
        return parent::setStudent_num($student_num);
    }

    public function setReal_name($real_name)
    {
        $this->__load();
        return parent::setReal_name($real_name);
    }

    public function setGender($gender)
    {
        $this->__load();
        return parent::setGender($gender);
    }

    public function setCollege($college)
    {
        $this->__load();
        return parent::setCollege($college);
    }

    public function setSpecialty($specialty)
    {
        $this->__load();
        return parent::setSpecialty($specialty);
    }

    public function setGrade($grade)
    {
        $this->__load();
        return parent::setGrade($grade);
    }

    public function setClass($class)
    {
        $this->__load();
        return parent::setClass($class);
    }

    public function setPhone($phone)
    {
        $this->__load();
        return parent::setPhone($phone);
    }

    public function setCheckin($checkin)
    {
        $this->__load();
        return parent::setCheckin($checkin);
    }

    public function setRoom($room)
    {
        $this->__load();
        return parent::setRoom($room);
    }

    public function setUser($user)
    {
        $this->__load();
        return parent::setUser($user);
    }

    public function getBuild()
    {
        $this->__load();
        return parent::getBuild();
    }

    public function setBuild($build)
    {
        $this->__load();
        return parent::setBuild($build);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getCreate_at()
    {
        $this->__load();
        return parent::getCreate_at();
    }

    public function setCreate_at($create_at)
    {
        $this->__load();
        return parent::setCreate_at($create_at);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'bed_num', 'student_num', 'real_name', 'gender', 'college', 'specialty', 'grade', 'class', 'phone', 'checkin', 'id', 'create_at', 'room', 'build', 'user');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}