<?php echo $this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('宿舍-soonseen.in')->setSeparator(' - ')->setAutoEscape(false) ?>
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')?>
    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')?>
    <!-- Scripts -->
    <?php echo $this->headScript()->prependFile($this->basePath() . '/js/jquery-flot/excanvas.min.js', 'text/javascript', array('conditional' => 'lte IE 8',))
                ->prependFile($this->basePath() . '/js/respond/respond.min.js', 'text/javascript', array('conditional' => 'lte IE 8',))
                ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ?>
</head>

<body>
    <div id="loading-block"></div>
    <div class="wraper sidebar-full">
        
        <?php echo $this->navigation('aside-navigation')->menu()->setPartial('application/partials/aside'); ?>
        <?php echo $this->navigation('header-navigation')->menu()->setPartial('application/partials/header'); ?>
        <div id="main">
            <div class="container-fluid">
                <div class="row-fluid">
                    <div class="span12">
                        <h3 class="page-title">宿舍管理系统</h3>
                        <ul class="breadcrumb">
                          <li>
                            <i class="icon-home"></i>
                            <a href="<?php echo $this->baseUrl() ?>">首页</a>
                            <span class="icon-angle-right"></span>
                          </li>
                        </ul>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span12">
                        <?php echo $this->content; ?>
                    </div>
                </div>
            </div>
            <footer id="footer">
                <div class="container-fluid">
                    2013 © <em>soonseen.in</em>
                    by
                    <a href="http://billyct.com/" target="_blank">billyct</a>
                    .
                </div>
            </footer>
        </div>
    </div>

    <!-- /container -->
    <script type="text/javascript">
    site = {
        baseUrl: "<?php echo $this->baseUrl() ?>"
    };
    </script>
    <?php echo $this->inlineScript()->prependFile($this->basePath() . '/js/app.js')
                                    ->prependFile($this->basePath() . '/js/extents.js')
                                    ->prependFile($this->basePath() . '/js/moment.min.js')
                                    ->prependFile($this->basePath() . '/js/placeholders/placeholders.min.js', 'text/javascript', array('conditional' => 'lte IE 8',))
                                    ->prependFile($this->basePath() . '/js/jquery-slimscroll/jquery.slimscroll.min.js')
                                    ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                    ->prependFile($this->basePath() . '/js/backbone-min.js')
                                    ->prependFile($this->basePath() . '/js/underscore-min.js')
                                    ->prependFile($this->basePath() . '/js/jquery-ui/js/jquery-ui-1.10.1.custom.min.js')
                                    ->prependFile($this->basePath() . '/js/jquery-1.9.1.min.js')
                                    ?>
    
</body>
</html>