<header>
            <nav class="navbar navbar-blue navbar-fixed-top social-navbar">
                <div class="navbar-inner">
                    <div class="container-fluid">
                        <a class="btn btn-navbar" data-toggle="collapse" data-target=".social-sidebar">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </a>
                        <a class="brand" href="../dashboard.html">soonseen.in</a>
                        <ul class="nav pull-right nav-indicators">
                            <li class="dropdown nav-messages">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <span class="badge">8</span>
                                    <i class="icon-envelope-alt"></i>
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="nav-messages-header">
                                        <a tabindex="-1" href="#">
                                            你有
                                            <strong>8</strong>
                                            条新消息
                                        </a>
                                    </li>
                                    <li class="nav-message-body">
                                        <a>
                                            <img src="/img/avatars/user-55x55.png" alt="User">
                                            <div>
                                                <small class="pull-right">Just Now</small>
                                                <strong>Julio Marquez</strong>
                                            </div>
                                            <div>Lorem ipsum dolor sit amet, consectetur...</div>
                                        </a>
                                    </li>

                                    <li class="nav-messages-footer">
                                        <a tabindex="-1" href="#">查看所有消息</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="divider-vertical"></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="icon-caret-down"></i>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="#">
                                            <i class="icon-user"></i>
                                            个人中心
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="icon-cogs"></i>
                                            设置
                                        </a>
                                    </li>
                                    <li>
                                        <a href="/user/signout">
                                            <i class="icon-off"></i>
                                            退出
                                        </a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="#">
                                            <i class="icon-info-sign"></i>
                                            帮助
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>